export const basic = [
    {
        roma: 'a',
        hira_han: '安',
        hira_han_unicode: '\u5b89',
        hira: 'あ',
        hira_unicode: '\u3042',
        kata: 'ア',
        kata_unicode: '\u30a2',
        kata_han: '阿',
        kata_han_unicode: '\u963f',
    },
    {
        roma: 'i',
        hira_han: '以',
        hira_han_unicode: '\u4ee5',
        hira: 'い',
        hira_unicode: '\u3044',
        kata: 'イ',
        kata_unicode: '\u30a4',
        kata_han: '伊',
        kata_han_unicode: '\u4f0a',
    },
    {
        roma: 'u',
        hira_han: '宇',
        hira_han_unicode: '\u5b87',
        hira: 'う',
        hira_unicode: '\u3046',
        kata: 'ウ',
        kata_unicode: '\u30a6',
        kata_han: '宇',
        kata_han_unicode: '\u5b87',
    },
    {
        roma: 'e',
        hira_han: '衣',
        hira_han_unicode: '\u8863',
        hira: 'え',
        hira_unicode: '\u3048',
        kata: 'エ',
        kata_unicode: '\u30a8',
        kata_han: '江',
        kata_han_unicode: '\u6c5f',
    },
    {
        roma: 'o',
        hira_han: '於',
        hira_han_unicode: '\u65bc',
        hira: 'お',
        hira_unicode: '\u304a',
        kata: 'オ',
        kata_unicode: '\u30aa',
        kata_han: '於',
        kata_han_unicode: '\u65bc',
    },
    {
        roma: 'ka',
        hira_han: '加',
        hira_han_unicode: '\u52a0',
        hira: 'か',
        hira_unicode: '\u304b',
        kata: 'カ',
        kata_unicode: '\u30ab',
        kata_han: '加',
        kata_han_unicode: '\u52a0',
    },
    {
        roma: 'ki',
        hira_han: '幾',
        hira_han_unicode: '\u5e7e',
        hira: 'き',
        hira_unicode: '\u304d',
        kata: 'キ',
        kata_unicode: '\u30ad',
        kata_han: '幾',
        kata_han_unicode: '\u5e7e',
    },
    {
        roma: 'ku',
        hira_han: '久',
        hira_han_unicode: '\u4e45',
        hira: 'く',
        hira_unicode: '\u304f',
        kata: 'ク',
        kata_unicode: '\u30af',
        kata_han: '久',
        kata_han_unicode: '\u4e45',
    },
    {
        roma: 'ke',
        hira_han: '計',
        hira_han_unicode: '\u8a08',
        hira: 'け',
        hira_unicode: '\u3051',
        kata: 'ケ',
        kata_unicode: '\u30b1',
        kata_han: '介',
        kata_han_unicode: '\u4ecb',
    },
    {
        roma: 'ko',
        hira_han: '己',
        hira_han_unicode: '\u5df1',
        hira: 'こ',
        hira_unicode: '\u3053',
        kata: 'コ',
        kata_unicode: '\u30b3',
        kata_han: '己',
        kata_han_unicode: '\u5df1',
    },
    {
        roma: 'sa',
        hira_han: '左',
        hira_han_unicode: '\u5de6',
        hira: 'さ',
        hira_unicode: '\u3055',
        kata: 'サ',
        kata_unicode: '\u30b5',
        kata_han: '散',
        kata_han_unicode: '\u6563',
    },
    {
        roma: 'shi',
        hira_han: '之',
        hira_han_unicode: '\u4e4b',
        hira: 'し',
        hira_unicode: '\u3057',
        kata: 'シ',
        kata_unicode: '\u30b7',
        kata_han: '之',
        kata_han_unicode: '\u4e4b',
    },
    {
        roma: 'su',
        hira_han: '寸',
        hira_han_unicode: '\u5bf8',
        hira: 'す',
        hira_unicode: '\u3059',
        kata: 'ス',
        kata_unicode: '\u30b9',
        kata_han: '須',
        kata_han_unicode: '\u9808',
    },
    {
        roma: 'se',
        hira_han: '世',
        hira_han_unicode: '\u4e16',
        hira: 'せ',
        hira_unicode: '\u305b',
        kata: 'セ',
        kata_unicode: '\u30bb',
        kata_han: '世',
        kata_han_unicode: '\u4e16',
    },
    {
        roma: 'so',
        hira_han: '曽',
        hira_han_unicode: '\u66fd',
        hira: 'そ',
        hira_unicode: '\u305d',
        kata: 'ソ',
        kata_unicode: '\u30bd',
        kata_han: '曽',
        kata_han_unicode: '\u66fd',
    },
    {
        roma: 'ta',
        hira_han: '太',
        hira_han_unicode: '\u592a',
        hira: 'た',
        hira_unicode: '\u305f',
        kata: 'タ',
        kata_unicode: '\u30bf',
        kata_han: '多',
        kata_han_unicode: '\u591a',
    },
    {
        roma: 'chi',
        hira_han: '知',
        hira_han_unicode: '\u77e5',
        hira: 'ち',
        hira_unicode: '\u3061',
        kata: 'チ',
        kata_unicode: '\u30c1',
        kata_han: '千',
        kata_han_unicode: '\u5343',
    },
    {
        roma: 'tsu',
        hira_han: '川',
        hira_han_unicode: '\u5ddd',
        hira: 'つ',
        hira_unicode: '\u3064',
        kata: 'ツ',
        kata_unicode: '\u30c4',
        kata_han: '川',
        kata_han_unicode: '\u5ddd',
    },
    {
        roma: 'te',
        hira_han: '天',
        hira_han_unicode: '\u5929',
        hira: 'て',
        hira_unicode: '\u3066',
        kata: 'テ',
        kata_unicode: '\u30c6',
        kata_han: '天',
        kata_han_unicode: '\u5929',
    },
    {
        roma: 'to',
        hira_han: '止',
        hira_han_unicode: '\u6b62',
        hira: 'と',
        hira_unicode: '\u3068',
        kata: 'ト',
        kata_unicode: '\u30c8',
        kata_han: '止',
        kata_han_unicode: '\u6b62',
    },
    {
        roma: 'na',
        hira_han: '奈',
        hira_han_unicode: '\u5948',
        hira: 'な',
        hira_unicode: '\u306a',
        kata: 'ナ',
        kata_unicode: '\u30ca',
        kata_han: '奈',
        kata_han_unicode: '\u5948',
    },
    {
        roma: 'ni',
        hira_han: '仁',
        hira_han_unicode: '\u4ec1',
        hira: 'に',
        hira_unicode: '\u306b',
        kata: 'ニ',
        kata_unicode: '\u30cb',
        kata_han: '仁',
        kata_han_unicode: '\u4ec1',
    },
    {
        roma: 'nu',
        hira_han: '奴',
        hira_han_unicode: '\u5974',
        hira: 'ぬ',
        hira_unicode: '\u306c',
        kata: 'ヌ',
        kata_unicode: '\u30cc',
        kata_han: '奴',
        kata_han_unicode: '\u5974',
    },
    {
        roma: 'ne',
        hira_han: '祢',
        hira_han_unicode: '\u7962',
        hira: 'ね',
        hira_unicode: '\u306d',
        kata: 'ネ',
        kata_unicode: '\u30cd',
        kata_han: '祢',
        kata_han_unicode: '\u7962',
    },
    {
        roma: 'no',
        hira_han: '乃',
        hira_han_unicode: '\u4e43',
        hira: 'の',
        hira_unicode: '\u306e',
        kata: 'ノ',
        kata_unicode: '\u30ce',
        kata_han: '乃',
        kata_han_unicode: '\u4e43',
    },
    {
        roma: 'ha',
        hira_han: '波',
        hira_han_unicode: '\u6ce2',
        hira: 'は',
        hira_unicode: '\u306f',
        kata: 'ハ',
        kata_unicode: '\u30cf',
        kata_han: '八',
        kata_han_unicode: '\u516b',
    },
    {
        roma: 'hi',
        hira_han: '比',
        hira_han_unicode: '\u6bd4',
        hira: 'ひ',
        hira_unicode: '\u3072',
        kata: 'ヒ',
        kata_unicode: '\u30d2',
        kata_han: '比',
        kata_han_unicode: '\u6bd4',
    },
    {
        roma: 'hu',
        roma2: 'fu',
        hira_han: '不',
        hira_han_unicode: '\u4e0d',
        hira: 'ふ',
        hira_unicode: '\u3075',
        kata: 'フ',
        kata_unicode: '\u30d5',
        kata_han: '不',
        kata_han_unicode: '\u4e0d',
    },
    {
        roma: 'he',
        hira_han: '部',
        hira_han_unicode: '\u90e8',
        hira: 'へ',
        hira_unicode: '\u3078',
        kata: 'ヘ',
        kata_unicode: '\u30d8',
        kata_han: '部',
        kata_han_unicode: '\u90e8',
    },
    {
        roma: 'ho',
        hira_han: '保',
        hira_han_unicode: '\u4fdd',
        hira: 'ほ',
        hira_unicode: '\u307b',
        kata: 'ホ',
        kata_unicode: '\u30db',
        kata_han: '保',
        kata_han_unicode: '\u4fdd',
    },
    {
        roma: 'ma',
        hira_han: '末',
        hira_han_unicode: '\u672b',
        hira: 'ま',
        hira_unicode: '\u307e',
        kata: 'マ',
        kata_unicode: '\u30de',
        kata_han: '末',
        kata_han_unicode: '\u672b',
    },
    {
        roma: 'mi',
        hira_han: '美',
        hira_han_unicode: '\u7f8e',
        hira: 'み',
        hira_unicode: '\u307f',
        kata: 'ミ',
        kata_unicode: '\u30df',
        kata_han: '三',
        kata_han_unicode: '\u4e09',
    },
    {
        roma: 'mu',
        hira_han: '武',
        hira_han_unicode: '\u6b66',
        hira: 'む',
        hira_unicode: '\u3080',
        kata: 'ム',
        kata_unicode: '\u30e0',
        kata_han: '牟',
        kata_han_unicode: '\u725f',
    },
    {
        roma: 'me',
        hira_han: '女',
        hira_han_unicode: '\u5973',
        hira: 'め',
        hira_unicode: '\u3081',
        kata: 'メ',
        kata_unicode: '\u30e1',
        kata_han: '女',
        kata_han_unicode: '\u5973',
    },
    {
        roma: 'mo',
        hira_han: '毛',
        hira_han_unicode: '\u6bdb',
        hira: 'も',
        hira_unicode: '\u3082',
        kata: 'モ',
        kata_unicode: '\u30e2',
        kata_han: '毛',
        kata_han_unicode: '\u6bdb',
    },
    {
        roma: 'ya',
        hira_han: '也',
        hira_han_unicode: '\u4e5f',
        hira: 'や',
        hira_unicode: '\u3084',
        kata: 'ヤ',
        kata_unicode: '\u30e4',
        kata_han: '也',
        kata_han_unicode: '\u4e5f',
    },
    {
        roma: '',
        hira_han: '',
        hira_han_unicode: '',
        hira: '',
        hira_unicode: '',
        kata: '',
        kata_unicode: '',
        kata_han: '',
        kata_han_unicode: '',
    },
    {
        roma: 'yu',
        hira_han: '由',
        hira_han_unicode: '\u7531',
        hira: 'ゆ',
        hira_unicode: '\u3086',
        kata: 'ユ',
        kata_unicode: '\u30e6',
        kata_han: '由',
        kata_han_unicode: '\u7531',
    },
    {
        roma: '',
        hira_han: '',
        hira_han_unicode: '',
        hira: '',
        hira_unicode: '',
        kata: '',
        kata_unicode: '',
        kata_han: '',
        kata_han_unicode: '',
    },
    {
        roma: 'yo',
        hira_han: '与',
        hira_han_unicode: '\u4e0e',
        hira: 'よ',
        hira_unicode: '\u3088',
        kata: 'ヨ',
        kata_unicode: '\u30e8',
        kata_han: '與',
        kata_han_unicode: '\u8207',
    },
    {
        roma: 'ra',
        hira_han: '良',
        hira_han_unicode: '\u826f',
        hira: 'ら',
        hira_unicode: '\u3089',
        kata: 'ラ',
        kata_unicode: '\u30e9',
        kata_han: '良',
        kata_han_unicode: '\u826f',
    },
    {
        roma: 'ri',
        hira_han: '利',
        hira_han_unicode: '\u5229',
        hira: 'り',
        hira_unicode: '\u308a',
        kata: 'リ',
        kata_unicode: '\u30ea',
        kata_han: '利',
        kata_han_unicode: '\u5229',
    },
    {
        roma: 'ru',
        hira_han: '留',
        hira_han_unicode: '\u7559',
        hira: 'る',
        hira_unicode: '\u308b',
        kata: 'ル',
        kata_unicode: '\u30eb',
        kata_han: '流',
        kata_han_unicode: '\u6d41',
    },
    {
        roma: 're',
        hira_han: '礼',
        hira_han_unicode: '\u793c',
        hira: 'れ',
        hira_unicode: '\u308c',
        kata: 'レ',
        kata_unicode: '\u30ec',
        kata_han: '礼',
        kata_han_unicode: '\u793c',
    },
    {
        roma: 'ro',
        hira_han: '呂',
        hira_han_unicode: '\u5442',
        hira: 'ろ',
        hira_unicode: '\u308d',
        kata: 'ロ',
        kata_unicode: '\u30ed',
        kata_han: '呂',
        kata_han_unicode: '\u5442',
    },
    {
        roma: 'wa',
        hira_han: '和',
        hira_han_unicode: '\u548c',
        hira: 'わ',
        hira_unicode: '\u308f',
        kata: 'ワ',
        kata_unicode: '\u30ef',
        kata_han: '和',
        kata_han_unicode: '\u548c',
    },
    {
        roma: '',
        hira_han: '',
        hira_han_unicode: '',
        hira: '',
        hira_unicode: '',
        kata: '',
        kata_unicode: '',
        kata_han: '',
        kata_han_unicode: '',
    },
    {
        roma: '',
        hira_han: '',
        hira_han_unicode: '',
        hira: '',
        hira_unicode: '',
        kata: '',
        kata_unicode: '',
        kata_han: '',
        kata_han_unicode: '',
    },
    {
        roma: '',
        hira_han: '',
        hira_han_unicode: '',
        hira: '',
        hira_unicode: '',
        kata: '',
        kata_unicode: '',
        kata_han: '',
        kata_han_unicode: '',
    },
    {
        roma: 'wo',
        hira_han: '遠',
        hira_han_unicode: '\u9060',
        hira: 'を',
        hira_unicode: '\u3092',
        kata: 'ヲ',
        kata_unicode: '\u30f2',
        kata_han: '乎',
        kata_han_unicode: '\u4e4e',
    },
    {
        roma: 'n',
        hira_han: '无',
        hira_han_unicode: '\u65e0',
        hira: 'ん',
        hira_unicode: '\u3093',
        kata: 'ン',
        kata_unicode: '\u30f3',
        kata_han: '尓',
        kata_han_unicode: '\u5c13',
    },
];
